name: Delete Workflow Runs

on:
  workflow_dispatch:
    inputs:
      retain_days:
        description: 'Days-worth of runs to keep for each workflow'
        default: '30'
      keep_minimum_runs:
        description: 'Minimum runs to keep for each workflow'
        default: '6'

jobs:
  build:
    name: Delete Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: ${{ github.event.inputs.retain_days }}
          keep_minimum_runs: ${{ github.event.inputs.keep_minimum_runs }}
